- name: ipa firewall
  hosts: auth_server
  become: true
  tasks:
   - firewalld:
        port: 80/tcp
        permanent: yes
        state: enabled
   - firewalld:
        port: 443/tcp
        permanent: yes
        state: enabled
   - firewalld:
        port: 389/tcp
        permanent: yes
        state: enabled
   - firewalld:
        port: 636/tcp
        permanent: yes
        state: enabled
   - firewalld:
        port: 88/udp
        permanent: yes
        state: enabled
   - firewalld:
        port: 88/tcp
        permanent: yes
        state: enabled
   - firewalld:
        port: 464/udp
        permanent: yes
        state: enabled
   - firewalld:
        port: 464/tcp
        permanent: yes
        state: enabled

   - firewalld:
        port: 53/tcp
        permanent: yes
        state: enabled
   - firewalld:
        port: 53/udp
        permanent: yes
        state: enabled
   - firewalld:
        port: 7369/tcp
        permanent: yes
        state: enabled
   - firewalld:
        zone: trusted
        interface: eth0
        permanent: yes
        state: enabled
   - name: restart firewalld
     service: name=firewalld state=restarted

- name: firewall others
  hosts: ['server', 'desktop']
  become: true
  tasks:
    - firewalld:
        zone: trusted
        interface: eth0
        permanent: yes
        state: enabled
    - name:
      service: name=firewalld state=restarted