- name: FTP Docker Container
  hosts: server
  become: true
  roles:
    - git
    - docker
  tasks:
    - name: file Make Directory
      file:
        path: /opt/ADS-Docker
        state: directory
        mode: 0775
    - name: git Docker Git Repo
      git:
        repo: "https://github.com/RealmOfTibbles/ADS-Docker.git"
        dest: /opt/ADS-Docker/
        clone: yes
        update: yes
        force: yes
    - name: shell build container
      shell:  docker build -t ftp /opt/ADS-Docker/ftp/
      args:
        chdir: /opt/ADS-Docker/ftp/
    - name: docker_volume files
      docker_volume:
        name: DataStore_ftp
        state: present
    - name: Run Container
      docker_container:
        name: ftp-Server
        image: "ftp"
        state: started
        restart: yes
        volumes:
        - DataStore_ftp/Data
        ports:
        - "21:21"
        - "20:20"
        cpu_shares: 768
        memory: 1024m
        cap_drop:
        - all
    - name: Get Containers Details
      shell: docker ps -l
      register: Output
    - name: Display Container Status's
      debug: var=Output.stdout_lines