- name: SMB Docker Container
  hosts: server
  become: true
  roles:
    - git
    - docker
  tasks:
    - name: file Make Directory
      file:
        path: /opt/ADS-Docker
        state: directory
        mode: 0775
    - name: git Docker Git Repo
      git:
        repo: "https://github.com/RealmOfTibbles/ADS-Docker.git"
        dest: /opt/ADS-Docker/
        clone: yes
        update: yes
        force: yes
    - name: shell build container
      shell:  docker build -t smb /opt/ADS-Docker/smb/
      args:
        chdir: /opt/ADS-Docker/FTP/
    - name: docker_volume files
      docker_volume:
        name: DataStore_smb
        state: present
    - name: Run Container
      docker_container:
        name: smb-Server
        image: "smb"
        state: started
        restart: yes
        volumes:
        - DataStore_smb/Data
        ports:
        - "139:139"
        - "445:445"
        - "137:137" # maybe needed
        - "138:138" # ^
        cpu_shares: 768
        memory: 1024m
        cap_drop:
        - all
    - name: Get Containers Details
      shell: docker ps -l
      register: Output
    - name: Display Container Status's
      debug: var=Output.stdout_lines